### PR TITLE
document PR validation

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
@adriaanm, review for accuracy?

**Comment by adriaanm** [comment]
LATM!

**Comment by adriaanm** [comment]
one key aspect to the design that I was reminded of is that naming (which is 1:1 for jenkins job and script in repo) is uniform across orgs & branches. `validate-main` is the name of the job conceptually, `scala-2.11.x-validate-main` is the jenkins name for the job running on 2.11.x in the scala org (since we can't make "virtual" jobs in jenkins that group by parameter, otherwise we wouldn't need this name mangling), and `scripts/jobs/validate/main` would be the name of the invoked script, except that `main` jobs are always flow DSL jobs, so there's no associated script

**Comment by SethTisue** [comment]
excellent. I added a second commit that works that in.

**Pull request merged**
