### PR TITLE
install nodejs/npm on workers

### PR DESCRIPTION
**Pull request by SethTisue**
for Scala.js. requested by @sjrd at scala/community-builds#276

### CODE REVIEW

**Comment by SethTisue** [comment]
I provisionally deployed this. here's what we see now on the workers:

```
ubuntu@ip-172-31-12-38:~$ nodejs --version
v4.2.6
ubuntu@ip-172-31-12-38:~$ node --version
The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
ubuntu@ip-172-31-12-38:~$ npm --version
The program 'npm' is currently not installed. You can install it by typing:
sudo apt install npm
```

the node version seems a bit old

**Comment by SethTisue** [comment]
the Chef cookbook we're using supports different installation methods. the default method is to use `apt`, and I checked that `sudo apt-get update` followed by `apt list --upgradable` doesn't show a newer version, so I guess that's just what the version of Ubuntu we're using offers?

@sjrd is it sufficient?

**Comment by SethTisue** [comment]
also does `nodejs` vs `node` matter?

trying a new test run at https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/300/console

**Comment by sjrd** [comment]
Yes, `nodejs` vs `node` matters. By default, Scala.js looks for `node`, but the `nodejs` thing is a known issue for Ubuntu, for which we have a workaround: add `jsEnv := NodeJSEnv(executable = "nodejs").value` in the settings of projects that need to run with Node.js. I'll update the PR on community-builds.

**Comment by SethTisue** [comment]
merged since latest community build runs are green.

but @adriaanm, you might want to give the Chef changes a once-over and make sure I didn't cargo-cult in some nonsense

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
