### PR TITLE
Dotty: test dotty bootstrapped and non-bootstrapped separately.

### PR DESCRIPTION
**Pull request by DarkDimius**
@adriaanm please review.

### CODE REVIEW

**Comment by adriaanm** [comment]
is the removal of the validate/scalastyle job intentional? if so, lgtm

**Comment by smarter** [comment]
Yes it is.

**Comment by SethTisue** [comment]
I'll put this into production shortly...

**Comment by SethTisue** [comment]
done, https://scala-ci.typesafe.com/view/dotty/job/dotty-master-validate-partest-bootstrapped/ exists now

**Comment by smarter** [comment]
@DarkDimius : I think we also need to update https://github.com/scala/scala-jenkins-infra/blob/master/templates/default/jobs/lampepfl/validate/main.xml.erb to replace scalastyle with partest-bootstrapped

**Pull request merged**
