### PR TITLE
allow passing ant options when building scala/scala

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by SethTisue** [comment]
nbd, but may I suggest calling it scala-build-opts instead of scala-ant-opts, in anticipation of the ant->sbt switchover?

**Comment by lrytz** [comment]
@SethTisue this too? :)

**Comment by SethTisue** [comment]
do you need me to also push this into production for you?

**Comment by lrytz** [comment]
if it's not a big deal, then that would be great

**Comment by SethTisue** [comment]
```
knife cookbook upload scala-jenkins-infra
ssh jenkins-master
sudo su --login
chef-client
```

log of chef-client run: https://gist.github.com/SethTisue/3202638a213379763fe9

**Pull request merged**
