### PR TITLE
re-enable CLA checking on Dotty repo

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by felixmulder** [comment]
Started this PR now without the webhook enabled: https://github.com/lampepfl/dotty/pull/1798

**Comment by SethTisue** [comment]
@felixmulder chef-client is running now on jenkins-master. until it finishes, this isn't live

**Comment by felixmulder** [comment]
Is the webhook to the Lightbend CI responsible for CLA-checking? If so, could we activate just that portion of the hook?

**Comment by SethTisue** [comment]
I hope that's what this PR does. chef-client finished, so you could try it now.

**Comment by felixmulder** [comment]
Looks like it is still running the validate-main portion in: https://github.com/lampepfl/dotty/pull/1800 with webhook enabled.

**Comment by SethTisue** [comment]
hmm. this would take some troubleshooting work.

unless @adriaanm sees an easy fix, I'm inclined to suggest you either 1) PR a fix yourself which I deploy for you, or 2) seek another CLA checker

**Comment by adriaanm** [comment]
What Seth said. Scabot was designed as a one-stop PR validation shop. If you'd like to reuse just the CLA checker, PRs welcome.

**Comment by felixmulder** [comment]
Sure :)

I'll try to get to it asap. Thanks for the help thus far guys.

**Pull request closed without merging**
