### PR TITLE
ignore community build failures on in release builds

### PR DESCRIPTION
**Pull request by lrytz**
@SethTisue wdyt?

### CODE REVIEW

**Comment by SethTisue** [comment]
ideally we'd do something better like have a "core community build" (required to succeed) and a "full community build" (allowed to fail), perhaps we'll do that eventually.

as for which way to flip the bit given the current situation, there is some recent discussion at https://github.com/scala/scala-jenkins-infra/issues/199. I'm a smidge more comfortable leaving it the way it is for now

**Comment by lrytz** [comment]
example run (where i've manually changed the jenkins config) here: https://scala-ci.typesafe.com/job/scala-2.12.x-release-main/715/console - in this case i killed the two community build jobs.

one problem is that the current setup prevents the `release-smoketest`, `release-website-archives` and `release-website-update-api` jobs from running.

**Comment by lrytz** [comment]
maybe we can just move the community build to the end?

**Comment by SethTisue** [comment]
preventing those jobs from running is kinda the point IMO, so that the nightly on the website is always one that has been fully vetted.

**Comment by lrytz** [comment]
you're probably right. i'm biased right now because i wanted to test the changes i made to the scripts :)

**Comment by SethTisue** [comment]
haha I was just writing a sentence that began: if your current motivation is that you just want to test that stuff without having to wait hours or days...

**Comment by SethTisue** [comment]
the end of the sentence is, maybe a Jenkins flag you can set to tell it to ignore the community build result. or just temporarily change it in the repo and then change it back when you're done.

**Comment by lrytz** [comment]
i did it with a temporary change in the jenkins UI.

**Pull request closed without merging**
