### PR TITLE
Enable colored output for all generated jobs

### PR DESCRIPTION
**Pull request by DarkDimius**

### CODE REVIEW

**Comment by adriaanm** [comment]
LGTM! Excellent work!

**Comment by adriaanm** [comment]
Looking forward to more :rainbow: in our logs.

**Comment by adriaanm** [comment]
Yay! Colors! https://scala-ci.typesafe.com/job/dotty-master-validate-partest/3/console

**Comment by DarkDimius** [comment]
@adriaanm for some reason this stopped working.
https://scala-ci.typesafe.com/job/dotty-master-validate-partest/35/console
Did you modify something?

**Comment by DarkDimius** [comment]
Ahh, disregards this. It's broken in pertest itself.

**Pull request merged**
