### PR TITLE
dotty job templates, scabot conf

### PR DESCRIPTION
**Pull request by adriaanm**
TODO: create a script in lampepfl/dotty with path `scripts/jobs/validate/main`,
inspired by https://github.com/scala/scala/tree/2.11.x/scripts/jobs/validate/publish-core,
that does something like:

```
baseDir=${WORKSPACE-`pwd`}
scriptsDir="$baseDir/scripts"
. $scriptsDir/common

update scala scala # note: do not do `cd ..`, so adjust your build to reflect scala/ is created in $baseDir
sbt -Ddotty.travis.build=yes update compile test scalastyle
```

Where scripts/common has:

```
update() {
  [[ -d $baseDir ]] || mkdir -p $baseDir
  cd $baseDir

  if [ ! -d $baseDir/$2 ]; then git clone "https://github.com/$1/$2.git"; fi

  cd $2

  git fetch --tags "https://github.com/$1/$2.git"
  (git fetch "https://github.com/$1/$2.git" $3 && git checkout -fq FETCH_HEAD) #|| git checkout -fq $3 # || fallback is for local testing on tag
  git reset --hard
}
```

### CODE REVIEW

**Comment by adriaanm** [comment]
This PR is a template for the dotty team to complete if they want to run on our CI infrastructure.

**Comment by adriaanm** [comment]
Our CI is ready to starting validating dotty PRs, as soon as this PR is completed & merged, and you add the necessary script to your repo, as explained above. Let me know how I can help further.

**Comment by adriaanm** [comment]
It's enough to add scala-jenkins to your collaborator team, as I already have authentication set up for the scala/scala repo, or you can create a dotty-specific user of course.

**Comment by DarkDimius** [comment]
@adriaanm, can you explain what is the advantage of running on typesafe infrastructure over running on EPFL one?
I've set up the Jenkins in EPFL today, and it took me several hours. It was pretty straightforward: https://scala-webapps.epfl.ch/jenkins/view/Dotty/job/Dotty/

If we move to typesafe infrastructure, I have several questions:
- where do we add users(Martin and me) to admins, to be able to white list pull-requests for testing?
- can we spawn several tasks in parallel? I already do this in https://scala-webapps.epfl.ch/jenkins/view/Dotty/job/Dotty/. I want to isolate different kinds of tests that we run, and make test suite succeed faster by running `partest` and `junit` as different jobs. This was easy to set up in jenkins, but I do not have understanding how this template-thing works.
- will we be able to access files of a failed build?

> It's enough to add scala-jenkins to your collaborator team

I've already did this. Unfortunately `scala-jenkins` needs to click a mail it received to agree to be added to the team. I guess it will also need to login to do so. Do you know who controls mail&password of `scala-jenkins`?

**Comment by adriaanm** [comment]
I'm absolutely fine with you running CI on EPFL's servers. @odersky asked me whether we could host your jenkins, so this is why I offered.

**Comment by adriaanm** [comment]
Our CI runs on EC2 (c4.2xlarge instances) and you can ssh directly to the machines. Everything is explained in detail in the README of this repo, which defines the infrastructure using chef recipes.

**Comment by adriaanm** [comment]
review by @DarkDimius

**Comment by DarkDimius** [comment]
LGTM, lets see if it is able to test https://github.com/lampepfl/dotty/pull/591

**Comment by adriaanm** [comment]
looks like it is! :-) :tada:

**Pull request merged**
