### PR TITLE
remove integrate-ide from non-2.11 build flows

### LINKED ISSUE #218: remove integrate-ide from 2.12 and 2.13 release flows
when integrate-ide stopped working in 2.12, we kludged it by putting this in scripts/jobs/integrate/ide in the scala/scala repo:

```
echo "IDE integration not yet available on 2.12.x. Punting."
exit 0
```

on the assumption it would be fixed soon. but that was at least a year ago. in the meantime, every 2.12 and 2.13 pull request says e.g.:

```
integrate-ide — [4238] SUCCESS. Took 21 s. Details
```

which is just misleading noise. I suggest we actually take it out of the 2.12 and 2.13 flows. if it were ever made to work for 2.12 and/or 2.13, we could always just revert the change.

cc @sschaef

### PR DESCRIPTION
**Pull request by SethTisue**
since it only works on 2.11 and it's been that way for a long time now

fixes #218

review by @adriaanm

### CODE REVIEW

**Comment by SethTisue** [comment]
(not tested yet since Adriaan is doing other scala-jenkins-infra work right now; Adriaan, if this looks plausible to you, I'll try actually running it)

**Comment by SethTisue** [comment]
this is live now. (ship it now, merge it later. that's how we roll.)

**Comment by SethTisue** [comment]
let's re-run a 2.11.x validate-main job and make sure it still runs integrate-ide: https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-validate-main/3089/consoleFull

and let's re-run a 2.12.x job and make sure it doesn't: https://scala-ci.typesafe.com/job/scala-2.12.x-validate-main/5002/consoleFull

we should also keep an eye on how any new scala/scala PRs that come in get handled.

**Comment by SethTisue** [comment]
doh:

```
ERROR: Failed to run DSL Script
groovy.lang.MissingPropertyException: No such property: branch for class: Script1
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:50)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:231)
	at Script1.run(Script1.groovy:27)
	at Script1$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at Script1$run.call(Unknown Source)
	at com.cloudbees.plugins.flow.FlowDSL.executeFlowScript(FlowDSL.groovy:84)
	at com.cloudbees.plugins.flow.FlowRun$FlyweightTaskRunnerImpl.run(FlowRun.java:219)
	at hudson.model.Run.execute(Run.java:1738)
	at com.cloudbees.plugins.flow.FlowRun.run(FlowRun.java:155)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```

I undid the change via chef.

I'll come back to this.

**Comment by adriaanm** [comment]
Will include in #238

**Pull request closed without merging**
