### PR TITLE
run Windows tests nightly

### PR DESCRIPTION
**Pull request by SethTisue**
would have done this a while ago if I'd known it was this easy...

already in production, first automatic run will be tonight.

### CODE REVIEW

**Comment by SethTisue** [comment]
oh, uh, @adriaanm, I see in my notes I had "nightly" written down one place, "weekly" written down another, not sure which you had in mind. (nightly seems fine to me.)

**Comment by adriaanm** [comment]
nightly is good -- weekly may have been in the context of the community build (on windows??)?

**Comment by SethTisue** [comment]
it's not Halloween anymore, don't scare me (by saying "community build" and "Windows" in the same sentence)

**Comment by adriaanm** [comment]
Wouldn't be that such a treat?

**Pull request merged**
